# Generated by hand for TanPit cooldown hourglass

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]
    operations = [
        migrations.AddField(
            model_name="pit",
            name="status_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="CooldownRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=20, unique=True)),
                ("minutes", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
